CREATE DATABASE MYTABLE

USE MYTABLE

CREATE TABLE MYTABLEINFO(ID INT IDENTITY,NAME VARCHAR (20), SURNAME VARCHAR(20),AGE INT, SALARY INT,MOBILE INT)

INSERT INTO MYTABLEINFO VALUES
('ROHIT','GUPTA',21,12200,92055464),
('ANKIT','GUPTA',22,10000,9206515),
('NITIN','GUPTA',23,14100,951655),
('SHIVAM','SHARMA',24,15200,92055),
('VIKAS','GUPKUMARTA',51,15200,9201555),
('MOHIT','SHARNA',26,15200,92051531),
('SOHIT','BANSAL',24,15200,920755),
('RAM','NIWAS',21,15200,85892055),
('VIPIN','GUATAM',22,15200,4592055),
('SANJAY','KUMAR',24,15200,9122055),
('ADI','RAI',25,14200,9292055),
('MANOJ','GUPTA',26,152000,3292055)

SELECT * FROM MYTABLEINFO

ALTER TABLE MYTABLEINFO 
ADD ADDRESS VARCHAR(50)

------------INSERT IN ADDRESS------



ALTER TABLE MYTABLEINFO 
DROP COLUMN ADDRESS


SELECT NAME,SURNAME,AGE FROM MYTABLEINFO WHERE SALARY= 15200;

UPDATE MYTABLEINFO 
SET SURNAME= 'MISHRA'
 WHERE ID =4

 SELECT ID ,NAME 
 FROM MYTABLEINFO 
 WHERE SALARY BETWEEN 12000 AND 14000

  SELECT ID ,NAME 
 FROM MYTABLEINFO 
 WHERE SURNAME  = 'GUPTA' AND SALARY=10000

 
  SELECT ID ,NAME 
 FROM MYTABLEINFO 
 WHERE SURNAME  = 'GUPTA' OR SALARY>12000

SELECT * FROM MYTABLEINFO

 SELECT ID ,NAME 
 FROM MYTABLEINFO 
 WHERE NOT SURNAME   = 'GUPTA' OR SALARY>12000

  SELECT ID ,NAME 
 FROM MYTABLEINFO 
 WHERE SURNAME  = 'GUPTA' AND NAME='ROHIT' 

  SELECT ID ,NAME 
 FROM MYTABLEINFO 
 WHERE SURNAME  = 'GUPTA' OR AGE>20

  SELECT ID ,NAME 
 FROM MYTABLEINFO 
 WHERE SURNAME  = 'GUPTA' AND SALARY>12000

  SELECT ID ,NAME 
 FROM MYTABLEINFO 
 WHERE SURNAME  LIKE'G%'
 
   SELECT ID ,NAME 
 FROM MYTABLEINFO 
 WHERE SURNAME  LIKE'%A'

 SELECT ID ,NAME 
 FROM MYTABLEINFO 
 WHERE SURNAME  LIKE'G%'

  SELECT ID ,NAME 
 FROM MYTABLEINFO 
 WHERE MOBILE  LIKE'9%_'

  SELECT ID ,NAME 
 FROM MYTABLEINFO 
 WHERE MOBILE  LIKE'9%'

  SELECT* FROM MYTABLEINFO
 WHERE ID BETWEEN 3 AND 6
 
  SELECT* FROM MYTABLEINFO
ORDER BY NAME,SALARY

 SELECT* FROM MYTABLEINFO
ORDER BY NAME ,SALARY
DESC

 SELECT  COUNT(NAME)
  FROM MYTABLEINFO

   SELECT  SUM(SALARY)
  FROM MYTABLEINFO

     SELECT  AVG(SALARY)
  FROM MYTABLEINFO

       SELECT  MAX(SALARY)
  FROM MYTABLEINFO

       SELECT  MIN(SALARY)
  FROM MYTABLEINFO
  MINSALARY

  SELECT NAME FROM MYTABLEINFO WHERE ID = 5

SP_RENAME 'MYTABLEINFO.SURNAME','LAST NAME'

---DELETE  FROM MTTABLEINFO WHERE ID=2


--TURUCATE MYTABLEINFO

SP_RENAME 'MYTABLEINFO','INFO' 

SELECT * FROM INFO

  SELECT COUNT(NAME),SUM(SALARY),SURNAME
  FROM MYTABLEINFO
  GROUP BY SURNAME


  ----------------------------JOINS-----------------------------------------
  CREATE TABLE MYDETAIL(DEPT_ID INT IDENTITY,ID INT,NAME VARCHAR(20),SALARY INT)
  INSERT INTO MYDETAIL VALUES
  (1,'ROHIT',20000),
  (3,'ANKIT',25000),
  (5,'NITIN',16000),
  (6,'SUNNY',12000),
  (7,'MOHIT',13000),
  (9,'SOHIT',17000),
  (10,'AAKASH',14000),
  (12,'PUROHIT',15000)

SELECT * FROM MYDETAIL

CREATE TABLE MYINFO(ID INT,CITY VARCHAR(20))
INSERT INTO MYINFO VALUES
(1,'GHAZIABAD'),
(2,'LONI'),
(3,'BULANDSHEHAR'),
(4,'HATRAS'),
(5,'BUNDELKHAND'),
(6,'BETIA'),
(7,'DEVRY')


SELECT * FROM MYDETAIL

------- INNER JOIN ------ 

SELECT * FROM MYINFO INNER JOIN MYDETAIL ON MYINFO.ID=MYDETAIL.ID
SELECT NAME,CITY FROM MYINFO INNER JOIN MYDETAIL ON MYINFO.ID=MYDETAIL.ID

---------RIGHT JOIN------------
SELECT * FROM MYINFO RIGHT JOIN MYDETAIL ON MYINFO.ID=MYDETAIL.ID 
SELECT NAME,CITY FROM MYINFO RIGHT JOIN MYDETAIL ON MYINFO.ID=MYDETAIL.ID

---------LEFT JOIN------------
SELECT * FROM MYINFO LEFT JOIN MYDETAIL ON MYINFO.ID=MYDETAIL.ID 
SELECT NAME,CITY FROM MYINFO LEFT JOIN MYDETAIL ON MYINFO.ID=MYDETAIL.ID

---------FULL JOIN------------
SELECT * FROM MYINFO FULL JOIN MYDETAIL ON MYINFO.ID=MYDETAIL.ID 
SELECT NAME,CITY FROM MYINFO FULL JOIN MYDETAIL ON MYINFO.ID=MYDETAIL.ID



  
